// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8FxFWj7V64Wh9F-PFHBJMtnpXZ0ftEEU',
    appId: '1:810481213035:web:bfb0ce9b1e239647319b2e',
    messagingSenderId: '810481213035',
    projectId: 'medica-app-a247f',
    authDomain: 'medica-app-a247f.firebaseapp.com',
    storageBucket: 'medica-app-a247f.firebasestorage.app',
    measurementId: 'G-JCRY7G9EL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAey1bP-UWQcaXC63JEFziL-39mHWv6O-k',
    appId: '1:810481213035:android:03f96056dbe555c6319b2e',
    messagingSenderId: '810481213035',
    projectId: 'medica-app-a247f',
    storageBucket: 'medica-app-a247f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHZyV8frhL0I-5461OKQXUIT_XSz9G-sg',
    appId: '1:810481213035:ios:5e81f2bdaff07c18319b2e',
    messagingSenderId: '810481213035',
    projectId: 'medica-app-a247f',
    storageBucket: 'medica-app-a247f.firebasestorage.app',
    iosBundleId: 'com.example.medicaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHZyV8frhL0I-5461OKQXUIT_XSz9G-sg',
    appId: '1:810481213035:ios:5e81f2bdaff07c18319b2e',
    messagingSenderId: '810481213035',
    projectId: 'medica-app-a247f',
    storageBucket: 'medica-app-a247f.firebasestorage.app',
    iosBundleId: 'com.example.medicaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8FxFWj7V64Wh9F-PFHBJMtnpXZ0ftEEU',
    appId: '1:810481213035:web:6812ab7e0207004e319b2e',
    messagingSenderId: '810481213035',
    projectId: 'medica-app-a247f',
    authDomain: 'medica-app-a247f.firebaseapp.com',
    storageBucket: 'medica-app-a247f.firebasestorage.app',
    measurementId: 'G-QYT2M33SQW',
  );
}
